### ISSUE TITLE
Fails to compile on kernel 6.17.0 and 7.0.0 (Ubuntu 24.04) — multiple DRM API changes

### ISSUE THREAD

**Issue by abdomustafa-ceo** [rhgndf/ms912x#43]
Trying to build ms912x on an up-to-date Ubuntu 24.04 system, testing against two kernels:

linux-image-7.0.0-28-generic
linux-image-6.17.0-35-generic

USB device confirmed as 534d:6021 MacroSilicon VGA Display Adapter.

Errors on kernel 7.0.0-28-generic
ms912x_transfer.c — from_timer() and del_timer_sync() are no longer declared (renamed upstream to timer_container_of() and timer_delete_sync()). Fixed locally by renaming these calls.
After fixing #1, a second error appears in ms912x_drv.c:
ms912x.h:16:21: error: initializer element is not computable at load time
   16 | #define DRIVER_DATE "20220101"
ms912x_drv.c:66:17: note: in expansion of macro 'DRIVER_DATE'
   66 |         .date = DRIVER_DATE,

It looks like struct drm_driver no longer has a .date member in this kernel version.

Also in ms912x_drv.c:
ms912x_drv.c:278:9: error: implicit declaration of function 'drm_fbdev_ttm_setup'
  278 |         drm_fbdev_ttm_setup(dev, 0);

drm_fbdev_ttm_setup() also appears to have been removed/renamed upstream.

Errors on kernel 6.17.0-35-generic

Same .date and drm_fbdev_ttm_setup errors as above did NOT reproduce identically — the .date error disappeared on this kernel, but drm_fbdev_ttm_setup was still missing:

ms912x_drv.c:278:9: error: implicit declaration of function 'drm_fbdev_ttm_setup'

I tried replacing this call with drm_client_setup(dev, NULL) plus #include <drm/drm_client.h>, but drm_client_setup is not declared anywhere in /usr/src/linux-headers-6.17.0-35-generic/include/, so that substitution was wrong too.

Request

Could the driver be updated to build against these newer kernels? Happy to test any patch or branch. Let me know if you need more info (dmesg, full build logs, etc).

**Comment by rhgndf** [comment]
Fixed in latest commits
